// ?CONCERN: JSON 파일로 변경할지 고민...

export const foreignTemplate = [
  {
    categoryName: "필수",
    categoryId: "category1",
    categoryColorTheme: "01",
    categoryOrder: 1,
    categoryElements: [
      {
        elementName: "여권",
        elementId: "category1-element1",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "볼펜",
        elementId: "category1-element2",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "여권사본",
        elementId: "category1-element3",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "여행자 보험",
        elementId: "category1-element4",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "숙소 예약증",
        elementId: "category1-element5",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "항공권",
        elementId: "category1-element6",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "E-티켓",
        elementId: "category1-element7",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "지갑",
        elementId: "category1-element8",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 8,
      },
      {
        elementName: "동전지갑",
        elementId: "category1-element9",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 9,
      },
      {
        elementName: "핸드폰",
        elementId: "category1-element10",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 10,
      },
      {
        elementName: "와이파이/유심",
        elementId: "category1-element11",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 11,
      },
      {
        elementName: "국제면허증",
        elementId: "category1-element12",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 12,
      },
      {
        elementName: "현지화폐",
        elementId: "category1-element13",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 13,
      },
      {
        elementName: "신용카드",
        elementId: "category1-element14",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 14,
      },
    ],
  },
  {
    categoryName: "의류",
    categoryId: "category2",
    categoryColorTheme: "02",
    categoryOrder: 2,
    categoryElements: [
      {
        elementName: "옷",
        elementId: "category2-element1",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "잠옷",
        elementId: "category2-element2",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "속옷",
        elementId: "category2-element3",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "양말",
        elementId: "category2-element4",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "신발",
        elementId: "category2-element5",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "수영복",
        elementId: "category2-element6",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "가방",
        elementId: "category2-element7",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "모자",
        elementId: "category2-element8",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 8,
      },
      {
        elementName: "선글라스",
        elementId: "category2-element9",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 9,
      },
    ],
  },
  {
    categoryName: "전자기기",
    categoryId: "category3",
    categoryColorTheme: "03",
    categoryOrder: 3,
    categoryElements: [
      {
        elementName: "충전기",
        elementId: "category3-element1",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "보조배터리",
        elementId: "category3-element2",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "충전케이블",
        elementId: "category3-element3",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "이어폰",
        elementId: "category3-element4",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "카메라",
        elementId: "category3-element5",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "메모리카드",
        elementId: "category3-element6",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "멀티어댑터",
        elementId: "category3-element7",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "삼각대",
        elementId: "category3-element8",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 8,
      },
    ],
  },
  {
    categoryName: "미용",
    categoryId: "category4",
    categoryColorTheme: "04",
    categoryOrder: 4,
    categoryElements: [
      {
        elementName: "스킨",
        elementId: "category4-element1",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "로션",
        elementId: "category4-element2",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "자외선 차단제(선크림)",
        elementId: "category4-element3",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "폼 클렌징",
        elementId: "category4-element4",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "바디워시",
        elementId: "category4-element5",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "왁스",
        elementId: "category4-element6",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "롤",
        elementId: "category4-element7",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "빗",
        elementId: "category4-element8",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 8,
      },
      {
        elementName: "머리끈",
        elementId: "category4-element9",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 9,
      },
      {
        elementName: "칫솔",
        elementId: "category4-element10",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 10,
      },
      {
        elementName: "치약",
        elementId: "category4-element11",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 11,
      },
      {
        elementName: "샴푸",
        elementId: "category4-element12",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 12,
      },
      {
        elementName: "린스",
        elementId: "category4-element13",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 13,
      },
      {
        elementName: "면도기",
        elementId: "category4-element14",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 14,
      },
      {
        elementName: "수건",
        elementId: "category4-element15",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 15,
      },
      {
        elementName: "화장솜",
        elementId: "category4-element16",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 16,
      },
      {
        elementName: "렌즈",
        elementId: "category4-element17",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 17,
      },
      {
        elementName: "인공눈물",
        elementId: "category4-element18",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 18,
      },
      {
        elementName: "면봉",
        elementId: "category4-element19",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 19,
      },
      {
        elementName: "티슈",
        elementId: "category4-element20",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 20,
      },
      {
        elementName: "물티슈",
        elementId: "category4-element21",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 21,
      },
      {
        elementName: "드라이기",
        elementId: "category4-element22",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 22,
      },
    ],
  },
  {
    categoryName: "상비약",
    categoryId: "category5",
    categoryColorTheme: "05",
    categoryOrder: 5,
    categoryElements: [
      {
        elementName: "종합감기약",
        elementId: "category5-element1",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "소화제",
        elementId: "category5-element2",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "지사제",
        elementId: "category5-element3",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "진통제",
        elementId: "category5-element4",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "멀미약",
        elementId: "category5-element5",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "반창고",
        elementId: "category5-element6",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "연고",
        elementId: "category5-element7",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "모기약",
        elementId: "category5-element8",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 8,
      },
      {
        elementName: "마스크",
        elementId: "category5-element9",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 9,
      },
      {
        elementName: "생리대",
        elementId: "category5-element10",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 10,
      },
    ],
  },
  {
    categoryName: "기타",
    categoryId: "category6",
    categoryColorTheme: "06",
    categoryOrder: 6,
    categoryElements: [
      {
        elementName: "담요",
        elementId: "category6-element1",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "우산",
        elementId: "category6-element2",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "슬리퍼",
        elementId: "category6-element3",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "지퍼백",
        elementId: "category6-element4",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "샤워기 필터",
        elementId: "category6-element5",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "우비",
        elementId: "category6-element6",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "안대",
        elementId: "category6-element7",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "귀마개",
        elementId: "category6-element8",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 8,
      },
      {
        elementName: "손톱깎이",
        elementId: "category6-element9",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 9,
      },
    ],
  },
];

export const domesticTemplate = [
  {
    categoryName: "필수",
    categoryId: "category1",
    categoryColorTheme: "01",
    categoryOrder: 1,
    categoryElements: [
      {
        elementName: "지갑",
        elementId: "category1-element1",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "핸드폰",
        elementId: "category1-element2",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "현금",
        elementId: "category1-element3",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "신용카드",
        elementId: "category1-element4",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 4,
      },
    ],
  },
  {
    categoryName: "의류",
    categoryId: "category2",
    categoryColorTheme: "02",
    categoryOrder: 2,
    categoryElements: [
      {
        elementName: "옷",
        elementId: "category2-element1",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "잠옷",
        elementId: "category2-element2",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "속옷",
        elementId: "category2-element3",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "양말",
        elementId: "category2-element4",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "신발",
        elementId: "category2-element5",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "수영복",
        elementId: "category2-element6",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "가방",
        elementId: "category2-element7",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "모자",
        elementId: "category2-element8",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 8,
      },
      {
        elementName: "선글라스",
        elementId: "category2-element9",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 9,
      },
      {
        elementName: "아쿠아슈즈",
        elementId: "category2-element10",
        elementColorTheme: "02",
        isChecked: false,
        elementOrder: 10,
      },
    ],
  },
  {
    categoryName: "전자기기",
    categoryId: "category3",
    categoryColorTheme: "03",
    categoryOrder: 3,
    categoryElements: [
      {
        elementName: "충전기",
        elementId: "category3-element1",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "보조배터리",
        elementId: "category3-element2",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "충전케이블",
        elementId: "category3-element3",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "이어폰",
        elementId: "category3-element4",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "카메라",
        elementId: "category3-element5",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "메모리카드",
        elementId: "category3-element6",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "삼각대",
        elementId: "category3-element7",
        elementColorTheme: "03",
        isChecked: false,
        elementOrder: 7,
      },
    ],
  },
  {
    categoryName: "미용",
    categoryId: "category4",
    categoryColorTheme: "04",
    categoryOrder: 4,
    categoryElements: [
      {
        elementName: "스킨",
        elementId: "category4-element1",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "로션",
        elementId: "category4-element2",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "자외선 차단제(선크림)",
        elementId: "category4-element3",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "폼 클렌징",
        elementId: "category4-element4",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "바디워시",
        elementId: "category4-element5",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "왁스",
        elementId: "category4-element6",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "롤",
        elementId: "category4-element7",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "빗",
        elementId: "category4-element8",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 8,
      },
      {
        elementName: "머리끈",
        elementId: "category4-element9",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 9,
      },
      {
        elementName: "칫솔",
        elementId: "category4-element10",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 10,
      },
      {
        elementName: "치약",
        elementId: "category4-element11",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 11,
      },
      {
        elementName: "샴푸",
        elementId: "category4-element12",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 12,
      },
      {
        elementName: "린스",
        elementId: "category4-element13",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 13,
      },
      {
        elementName: "면도기",
        elementId: "category4-element14",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 14,
      },
      {
        elementName: "수건",
        elementId: "category4-element15",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 15,
      },
      {
        elementName: "화장솜",
        elementId: "category4-element16",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 16,
      },
      {
        elementName: "렌즈",
        elementId: "category4-element17",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 17,
      },
      {
        elementName: "인공눈물",
        elementId: "category4-element18",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 18,
      },
      {
        elementName: "면봉",
        elementId: "category4-element19",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 19,
      },
      {
        elementName: "티슈",
        elementId: "category4-element20",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 20,
      },
      {
        elementName: "물티슈",
        elementId: "category4-element21",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 21,
      },
      {
        elementName: "드라이기",
        elementId: "category4-element22",
        elementColorTheme: "04",
        isChecked: false,
        elementOrder: 22,
      },
    ],
  },
  {
    categoryName: "상비약",
    categoryId: "category5",
    categoryColorTheme: "05",
    categoryOrder: 5,
    categoryElements: [
      {
        elementName: "종합감기약",
        elementId: "category5-element1",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "소화제",
        elementId: "category5-element2",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "지사제",
        elementId: "category5-element3",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "진통제",
        elementId: "category5-element4",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "멀미약",
        elementId: "category5-element5",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "반창고",
        elementId: "category5-element6",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "연고",
        elementId: "category5-element7",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "모기약",
        elementId: "category5-element8",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 8,
      },
      {
        elementName: "마스크",
        elementId: "category5-element9",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 9,
      },
      {
        elementName: "생리대",
        elementId: "category5-element10",
        elementColorTheme: "05",
        isChecked: false,
        elementOrder: 10,
      },
    ],
  },
  {
    categoryName: "기타",
    categoryId: "category6",
    categoryColorTheme: "06",
    categoryOrder: 6,
    categoryElements: [
      {
        elementName: "우산",
        elementId: "category6-element1",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "슬리퍼",
        elementId: "category6-element2",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 2,
      },
      {
        elementName: "지퍼백",
        elementId: "category6-element3",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 3,
      },
      {
        elementName: "샤워기 필터",
        elementId: "category6-element4",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 4,
      },
      {
        elementName: "우비",
        elementId: "category6-element5",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 5,
      },
      {
        elementName: "안대",
        elementId: "category6-element6",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 6,
      },
      {
        elementName: "귀마개",
        elementId: "category6-element7",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 7,
      },
      {
        elementName: "손톱깎이",
        elementId: "category6-element8",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 8,
      },
      {
        elementName: "돗자리",
        elementId: "category6-element9",
        elementColorTheme: "06",
        isChecked: false,
        elementOrder: 9,
      },
    ],
  },
];

export const basicTemplate = [
  {
    categoryName: "중요",
    categoryId: "category1",
    categoryColorTheme: "01",
    categoryOrder: 1,
    categoryElements: [
      {
        elementName: "지갑",
        isChecked: false,
      },
      {
        elementName: "핸드폰",
        isChecked: false,
      },
    ],
  },
  {
    categoryName: "필수",
    categoryId: "category1",
    categoryColorTheme: "01",
    categoryOrder: 1,
    categoryElements: [
      {
        elementName: "지갑",
        elementId: "category1-element1",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 1,
      },
      {
        elementName: "핸드폰",
        elementId: "category1-element2",
        elementColorTheme: "01",
        isChecked: false,
        elementOrder: 2,
      },
    ],
  },
];
